# worktree_dir: .worktrees/
nerdfont: true
agent: claude
merge_strategy: rebase
panes:
  - command: <agent>
    focus: true
files:
  symlink:
    - .artifacts
    - .plans
    - node_modules
    - docs/superpowers
status_icons:
  working: "󰚩"
  waiting: "󰍡"
  done: "󰄬"
