{
  imports = [
    ./agent-indicator.nix
    ./agents.nix
    ./ai.nix
    ./annot.nix
    ./anthropic-skills.nix
    ./betterfox.nix
    ./basic-memory.nix
    ./claude-code.nix
    ./crush.nix
    ./impeccable.nix
    ./jscpd.nix
    ./plannotator.nix
    ./playwriter.nix
    ./superpowers.nix
    ./taste-skill.nix
  ];
}
